---

download_mbit: &download_mbit
  entity: sensor.speedtest_download
  type: gauge
  name: Download
  title: Download Mbit/s
  unit: mbit/s
  min: 0
  max: 500
  severity:
    green: 450
    yellow: 100
    red: 0

internet_latency: &internet_latency
  entity: sensor.speedtest_ping
  type: gauge
  name: Latency
  title: Latancy ms
  unit: ms
  min: 0
  max: 20
  severity:
    green: 0
    yellow: 10
    red: 15

title: Casita
views:
  - !include views/home/home.yaml
  - badges: []
    title: Extra
    icon: mdi:cog
    cards:
      - *download_mbit
      - *internet_latency
      - type: entity
        entity: binary_sensor.verisure_ethernet_status
      - type: entity
        entity: sensor.unifi_dream_machine_b_sent
      - type: entity
        entity: sensor.unifi_dream_machine_b_received
      - type: entity
        entity: sensor.electricity_price_mosshagestigen_67
