- alias: "STORAGE: Change storage light when door open/closes"
  trigger:
    platform: state
    entity_id: binary_sensor.fibaro_door_window_sensor_2_access_control_window_door_is_open
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.fibaro_door_window_sensor_2_access_control_window_door_is_open
              state: 'on'
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.storage
                brightness: 255
        - conditions:
            - condition: state
              entity_id: binary_sensor.fibaro_door_window_sensor_2_access_control_window_door_is_open
              state: 'off'
          sequence:
            - service: light.turn_off
              data:
                entity_id: light.storage
