---

homeassistant:
  name: Home
  longitude: !secret home_longitude
  latitude: !secret home_latitude
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
config:
frontend:
history:
image:
input_number:
input_select:
logbook:
map:
media_source:
mobile_app:
ssdp:
sun:
system_health:
tag:
updater:
zeroconf:
person:

tradfri:
  host: 192.168.1.249
tibber:
  access_token: !secret tibber_access_token
recorder:
tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: eu-west-1
    voice: Joanna
    sample_rate: 22050
    engine: neural
    text_type: ssml
speedtestdotnet:
tesla:
  username: !secret tesla_username
  password: !secret tesla_password
  scan_interval: 60
sonos:
verisure:
  username: !secret verisure_username
  password: !secret verisure_password
ios:
  actions:
    - name: party
      background_color: "#000000"
      label:
        text: "Party Scene"
        color: "#ff0000"
      icon:
        icon: emoticon-excited
        color: "#ffffff"
    - name: latin
      background_color: "#000000"
      label:
        text: "Latin Scene"
        color: "#ff0000"
      icon:
        icon: creation
        color: "#ffffff"
    - name: chill
      background_color: "#000000"
      label:
        text: "Chill Scene"
        color: "#ff0000"
      icon:
        icon: grill
        color: "#ffffff"
#  push:
#    categories:
#      - name: Open I.C.E
#        identifier: 'open_ice'
#        actions:
#          - identifier: 'OPEN_CAR'
#            title: 'Open Car'
#            activationMode: 'background'
#            authenticationRequired: true
#            destructive: false
#            behavior: 'default'
#      - name: Home Assistant
#        identifier: 'home_assistant'
#        actions:
#          - identifier: 'HOME_ASSISTANT'
#            title: Home Assistant
#            activationMode: 'background'
#            authenticationRequired: false
#            destructive: false
#            behavior: 'default'
upnp:
hue:
  bridges:
    - host: 192.168.1.200
      allow_unreachable: true
      allow_hue_groups: false
    - host: 192.168.1.238
      allow_unreachable: true
      allow_hue_groups: false
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token

binary_sensor:
  - platform: iss

emulated_hue:
  listen_port: 80
  host_ip: 192.168.1.2
  expose_by_default: false
  entities:
    light.bedroom:
      hidden: false

homekit:
  - filter:
      include_entities:
        - light.kitchen
        - light.hallway
        - light.staircase
        - light.living_room
        - light.office
        - light.guest_room
        - light.bedroom
        - light.closet
        - sensor.i_c_e_temperature_sensor_inside
        - sensor.i_c_e_mileage_sensor

sensor: !include sensors.yaml
media_player: !include media_players.yaml
group: !include groups.yaml
automation: !include_dir_merge_list  automations/
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml

device_tracker:
  - platform: icloud3
    username: !secret icloud_joatin_username
    password: !secret icloud_joatin_password
    tracking_method: famshr
    track_devices:
      - silver
      - joatins_ipad
      - joatins_iphone
      - joatins_apple_watch

lovelace:
  mode: yaml
  resources:
    - url: local/lovelace/auto-entities.js?v=0.0.1
      type: module
    - url: local/lovelace/button-card.js?v=0.0.1
      type: module
    - url: local/lovelace/card-mod.js?v=0.0.1
      type: module
    - url: local/lovelace/card-tools.js?v=0.0.1
      type: module
    - url: local/lovelace/mini-graph-card-bundle.js?v=0.0.1
      type: module
    - url: local/lovelace/state-switch.js?v=0.0.1
      type: module
    - url: local/lovelace/swipe-card.js?v=0.0.1
      type: module
    - url: local/lovelace/layout-card.js?v=0.0.1
      type: module
    - url: local/lovelace/mini-media-player-bundle.js?v=0.0.1
      type: module
    - url: local/lovelace/light-popup-card.js?v=0.0.1
      type: module
    - url: /browser_mod.js
      type: module
  dashboards:
    homekit-infused:
      mode: yaml
      title: Dashboard
      icon: mdi:home-assistant
      show_in_sidebar: true
      filename: lovelace/base.yaml

lovelace_gen:
browser_mod:
