---

homeassistant:
  name: Home
  longitude: !secret home_longitude
  latitude: !secret home_latitude
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
config:
frontend:
history:
image:
input_number:
input_select:
logbook:
map:
media_source:
mobile_app:
ssdp:
sun:
system_health:
tag:
updater:
zeroconf:
person:
python_script:
stream:
cloud:
  google_actions:
    filter:
      include_domains:
        - light
        - cover
        - media_player

tradfri:
  host: 192.168.1.249
tibber:
  access_token: !secret tibber_access_token
recorder:
tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: eu-west-1
    voice: Joanna
    sample_rate: 22050
    engine: neural
    text_type: ssml
speedtestdotnet:
sonos:
#  push:
#    categories:
#      - name: Open I.C.E
#        identifier: 'open_ice'
#        actions:
#          - identifier: 'OPEN_CAR'
#            title: 'Open Car'
#            activationMode: 'background'
#            authenticationRequired: true
#            destructive: false
#            behavior: 'default'
#      - name: Home Assistant
#        identifier: 'home_assistant'
#        actions:
#          - identifier: 'HOME_ASSISTANT'
#            title: Home Assistant
#            activationMode: 'background'
#            authenticationRequired: false
#            destructive: false
#            behavior: 'default'
hue:
  bridges:
    - host: 192.168.1.200
      allow_unreachable: true
      allow_hue_groups: false
    - host: 192.168.1.238
      allow_unreachable: true
      allow_hue_groups: false

binary_sensor:
  - platform: iss

emulated_hue:
  listen_port: 80
  host_ip: 192.168.1.2
  expose_by_default: false
  entities:
    light.bedroom:
      hidden: false
    light.closet:
      hidden: false
    light.office:
      hidden: false
    light.guest_room:
      hidden: false
    light.staircase:
      hidden: false
    light.kitchen:
      hidden: false
    light.hallway:
      hidden: false
    light.living_room:
      hidden: false

homekit:
  - filter:
      include_domains:
        - person
        - alarm_control_panel
        - camera
      include_entities:
        - sensor.i_c_e_temperature_sensor_inside
        - sensor.sovrum_temperature
        - sensor.hall_temperature
        - sensor.fibaro_door_window_sensor_2_air_temperature
        - sensor.vardagsrum_temperature
        - sensor.temperature_3
        - cover.flush_shutter_dc
    entity_config:
      cover.flush_shutter_dc:
        name: Living Room Blinds
      sensor.sovrum_temperature:
        name: Bedroom Temperature
      sensor.hall_temperature:
        name: Hallway Temperature
      sensor.fibaro_door_window_sensor_2_air_temperature:
        name: Storage Temperature
        linked_battery_sensor: sensor.fibaro_door_window_sensor_2_battery_level
      sensor.vardagsrum_temperature:
        name: Living Room Temperature
      sensor.temperature_3:
        name: Closet Temperature
        linked_battery_sensor: sensor.motion_sensor_battery_level
      camera.doorbell:
        support_audio: False
        max_fps: 45
  - name: Front Door Lock
    port: 21065
    mode: accessory
    filter:
      include_entities:
        - lock.ytterdorr
    entity_config:
      lock.ytterdorr:
        name: Lock Front Door

shell_command: !include shell_commands.yaml
sensor: !include sensors.yaml
media_player: !include media_players.yaml
group: !include groups.yaml
automation: !include_dir_merge_list  automations/
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
zone: !include zones.yaml
input_boolean: !include input_booleans.yaml

home_connect:
  client_id: !secret bosch_client_id
  client_secret: !secret bosch_client_secret

lovelace:
  mode: yaml
  resources:
    - url: local/lovelace/auto-entities.js?v=0.0.1
      type: module
    - url: local/lovelace/button-card.js?v=0.0.1
      type: module
    - url: local/lovelace/card-mod.js?v=0.0.1
      type: module
    - url: local/lovelace/card-tools.js?v=0.0.1
      type: module
    - url: local/lovelace/mini-graph-card-bundle.js?v=0.0.1
      type: module
    - url: local/lovelace/state-switch.js?v=0.0.1
      type: module
    - url: local/lovelace/swipe-card.js?v=0.0.1
      type: module
    - url: local/lovelace/layout-card.js?v=0.0.1
      type: module
    - url: local/lovelace/mini-media-player-bundle.js?v=0.0.1
      type: module
    - url: local/lovelace/light-popup-card.js?v=0.0.1
      type: module
    - url: local/lovelace/light-entity-card.js?v=0.0.1
      type: module
    - url: /browser_mod.js
      type: module
  dashboards:
    homekit-infused:
      mode: yaml
      title: Dashboard
      icon: mdi:home-assistant
      show_in_sidebar: true
      filename: lovelace/base.yaml

lovelace_gen:
browser_mod:
