version: '3'
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    ports:
      - 8123:8123
      - 1400:1400
    environment:
      - TZ=Europe/Stockholm
    volumes:
      - ./config:/config
    restart: always

