---

- platform: time_date
  display_options:
    - time
    - date
    - date_time
    - date_time_iso
    - time_date
    - time_utc
    - beat

- platform: systemmonitor
  resources:
    - type: disk_use
      arg: /home
    - type: disk_free
      arg: /home
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: memory_use
    - type: memory_use_percent
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: ipv4_address
      arg: eth0
    - type: packets_in
      arg: eth0
    - type: packets_out
      arg: eth0
    - type: processor_use

# Frontend Greeting
- platform: template
  sensors:
    greeting:
      friendly_name: Greeting
      value_template: >-
        {% set time = states('sensor.time') %}
        {% if '00:00' < time < '06:00' %}
          Good night! 🌙
        {% elif '06:00' < time < '12:00' %}
          Good morning!
        {% elif '12:00' < time < '18:00' %}
          Good afternoon!
        {% else %}
          Good evening
        {% endif %}
