profile_card: &profile_card
  aspect_ratio: '1:1'
  state_filter:
    "not_home": grayscale(90%)
  show_name: false
  show_state: true
  type: picture-entity


title: Casita
resources:
  - url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
    type: module
  - url: local/lovelace/custom-header.js?v=1.7.9
    type: module
views:
  - badges: []
    title: Overview
    cards:
      - cards:
          - cards:
              - <<: *profile_card
                entity: person.joatin
                image: local/images/joatin.jpeg?v=1
                tap_action:
                  action: call-service
                  service: browser_mod.popup
                  service_data:
                    title: Joatin
                    card:
                      type: entities
                      entities:
                        - sensor.iphone_battery_level_2
                        - sensor.joatins_ipad_battery_level
                        - sensor.silver_battery_state
                        - sensor.joatins_apple_watch_battery_state
                    deviceID:
                      - this
                      - dashboard
              - <<: *profile_card
                entity: person.caroline
                image: local/images/caroline.jpeg?v=1
                tap_action:
                  action: call-service
                  service: browser_mod.popup
                  service_data:
                    title: Caroline
                    card:
                      type: entities
                      entities:
                        - sensor.carolines_iphone_battery_level
                        - sensor.carolines_apple_watch_battery_state
                        - sensor.carolines_macbook_pro_battery_state
                    deviceID:
                      - this
                      - dashboard
            type: horizontal-stack
          - entity: media_player.living_room
            type: media-control
          - entity: weather.smhi_home
            type: custom:weather-card
        type: vertical-stack
      - cards:
          - type: button
            name: Party Time
            show_state: false
            show_icon: true
            icon: fas:laugh-beam
            tap_action:
              action: call-service
              service: script.party
          - type: button
            name: Chill
            show_state: false
            show_icon: true
            icon: mdi:human-female-dance
            tap_action:
              action: call-service
              service: script.party
        type: vertical-stack
  - badges: []
    title: Tesla
    cards:
      - cards:
          - entity: sensor.i_c_e_range_sensor
            type: gauge
            name: Range
            title: I.C.E Battery Range
            unit: km
            min: 0
            max: 560
            severity:
              green: 100
              yellow: 40
              red: 0
          - type: button
            name: Heat Tesla
            show_state: true
            tap_action:
              action: call-service
              service: script.heat_tesla
            hold_action:
              action: toggle
            entity: climate.i_c_e_hvac_climate_system
          - entities:
              - entity: lock.i_c_e_door_lock
              - entity: binary_sensor.i_c_e_charger_sensor
              - entity: climate.i_c_e_hvac_climate_system
            show_name: false
            title: I.C.E
            type: glance
          - entity: sensor.i_c_e_battery_sensor
            graph: line
            hours_to_show: 72
            type: sensor
        type: vertical-stack