---

profile_card: &profile_card
  aspect_ratio: '1:1'
  state_filter:
    "not_home": grayscale(90%)
  show_name: false
  show_state: true
  type: picture-entity

profile_cards: &profile_cards
  type: horizontal-stack
  cards:
    - <<: *profile_card
      entity: person.joatin
      image: local/images/joatin.jpeg?v=1
      tap_action:
        action: call-service
        service: browser_mod.popup
        service_data:
          title: Joatin
          card:
            type: vertical-stack
            cards:
              - type: entities
                entities:
                  - sensor.joatins_iphone_battery_state_2
                  - sensor.joatins_ipad_battery_level
                  - sensor.silver_battery_state
                  - sensor.joatins_apple_watch_battery_state
              - type: horizontal-stack
                cards:
                  - type: button
                    name: Find iPhone
                    show_state: false
                    icon: mdi:cellphone
                    icon_height: 2em
                    tap_action:
                      action: call-service
                      service: icloud.play_sound
                      service_data:
                        account: granlundjoatin@icloud.com
                        device_name: Joatin's iPhone
                  - type: button
                    name: Find iPad
                    show_state: false
                    icon: mdi:tablet-ipad
                    icon_height: 2em
                    tap_action:
                      action: call-service
                      service: icloud.play_sound
                      service_data:
                        account: granlundjoatin@icloud.com
                        device_name: Joatin's iPad
                  - type: button
                    name: Find Watch
                    show_state: false
                    icon: mdi:watch
                    icon_height: 2em
                    tap_action:
                      action: call-service
                      service: icloud.play_sound
                      service_data:
                        account: granlundjoatin@icloud.com
                        device_name: Joatin's Watch
          deviceID:
            - this
            - dashboard
    - <<: *profile_card
      entity: person.caroline
      image: local/images/caroline.jpeg?v=1
      tap_action:
        action: call-service
        service: browser_mod.popup
        service_data:
          title: Caroline
          card:
            type: entities
            entities:
              - sensor.carolines_iphone_battery_level
              - sensor.carolines_apple_watch_battery_state
              - sensor.carolines_macbook_pro_battery_state
          deviceID:
            - this
            - dashboard

tesla_range: &tesla_range
  entity: sensor.i_c_e_range_sensor
  type: gauge
  name: Range
  title: I.C.E Battery Range
  unit: km
  min: 0
  max: 560
  severity:
    green: 112
    yellow: 56
    red: 0

tesla_heat: &tesla_heat
  type: button
  name: Heat Tesla
  show_state: true
  tap_action:
    action: call-service
    service: script.heat_tesla
  hold_action:
    action: toggle
  entity: climate.i_c_e_hvac_climate_system

download_mbit: &download_mbit
  entity: sensor.speedtest_download
  type: gauge
  name: Download
  title: Download Mbit/s
  unit: mbit/s
  min: 0
  max: 500
  severity:
    green: 450
    yellow: 100
    red: 0

internet_latency: &internet_latency
  entity: sensor.speedtest_ping
  type: gauge
  name: Latency
  title: Latancy ms
  unit: ms
  min: 0
  max: 20
  severity:
    green: 0
    yellow: 10
    red: 15

title: Casita
resources:
  - url: local/lovelace/auto-entities.js?v=0.0.1
    type: module
  - url: local/lovelace/button-card.js?v=0.0.1
    type: module
  - url: local/lovelace/card-mod.js?v=0.0.1
    type: module
  - url: local/lovelace/card-tools.js?v=0.0.1
    type: module
  - url: local/lovelace/mini-graph-card-bundle.js?v=0.0.1
    type: module
  - url: local/lovelace/state-switch.js?v=0.0.1
    type: module
  - url: local/lovelace/swipe-card.js?v=0.0.1
    type: module
  - url: local/lovelace/layout-card.js?v=0.0.1
    type: module
  - url: /browser_mod.js
    type: module
views:
  - !include
    - lovelace/views/home/home.yaml
  - badges: []
    title: Overview
    icon: mdi:home
    cards:
      - *profile_cards
      - entity: media_player.living_room
        type: media-control
      - type: horizontal-stack
        cards:
          - *tesla_range
          - *tesla_heat
      - entity: weather.smhi_home
        type: custom:weather-card
      - cards:
          - type: button
            name: Party
            show_state: false
            show_icon: true
            icon: mdi:emoticon-excited
            tap_action:
              action: call-service
              service: script.scene_party
          - type: button
            name: Latin
            show_state: false
            show_icon: true
            icon: mdi:creation
            tap_action:
              action: call-service
              service: script.party
          - type: button
            name: Chill
            show_state: false
            show_icon: true
            icon: mdi:grill
            tap_action:
              action: call-service
              service: script.party
        type: horizontal-stack
      - type: custom:button-card
        entity: input_boolean.guest_mode
        icon: mdi:human-greeting
        color_type: card
        show_name: false
        show_state: true
        tap_action:
          action: toggle
  - badges: []
    title: Lights
    icon: mdi:lamp
    cards:
      - type: light
        entity: light.hallway
      - type: light
        entity: light.staircase
      - type: light
        entity: light.kitchen
      - type: light
        entity: light.bedroom
      - type: light
        entity: light.office
      - type: light
        entity: light.guest_room
      - type: light
        entity: light.living_room
  - badges: []
    title: Tesla
    icon: mdi:car
    cards:
      - cards:
          - *tesla_range
          - *tesla_heat
          - entities:
              - entity: lock.i_c_e_door_lock
              - entity: binary_sensor.i_c_e_charger_sensor
              - entity: climate.i_c_e_hvac_climate_system
            show_name: false
            title: I.C.E
            type: glance
          - entity: sensor.i_c_e_battery_sensor
            graph: line
            hours_to_show: 72
            type: sensor
        type: vertical-stack
  - badges: []
    title: Extra
    icon: mdi:cog
    cards:
      - *download_mbit
      - *internet_latency
      - type: entity
        entity: binary_sensor.verisure_ethernet_status
      - type: entity
        entity: sensor.unifi_dream_machine_b_sent
      - type: entity
        entity: sensor.unifi_dream_machine_b_received
      - type: entity
        entity: sensor.electricity_price_mosshagestigen_67
