title: Casita
views:
  - badges: []
    title: Overview
    cards:
      - cards:
          - cards:
              - aspect_ratio: 0%
                entity: person.joatin
                image: 'https://demo.home-assistant.io/stub_config/bedroom.png'
                show_name: false
                show_state: true
                type: picture-entity
              - aspect_ratio: 0%
                entity: switch.i_c_e_update_switch
                image: 'https://demo.home-assistant.io/stub_config/bedroom.png'
                type: picture-entity
            type: horizontal-stack
          - entity: weather.smhi_home
            type: weather-forecast
          - entity: media_player.living_room
            type: media-control
        type: vertical-stack
      - cards:
          - entities:
              - entity: lock.i_c_e_door_lock
              - entity: binary_sensor.i_c_e_charger_sensor
              - entity: climate.i_c_e_hvac_climate_system
            show_name: false
            title: I.C.E
            type: glance
          - entity: sensor.i_c_e_battery_sensor
            graph: line
            hours_to_show: 72
            type: sensor
          - entity: sensor.i_c_e_range_sensor
            type: gauge
            name: Range
            unit: km
            min: 0
            max: 560
            severity:
              green: 100
              yellow: 40
              red: 0
        type: vertical-stack
  - badges: []
    title: Tesla
    cards:
      - cards:
          - cards:
              - entities:
                  - entity: lock.i_c_e_door_lock
                  - entity: binary_sensor.i_c_e_charger_sensor
                  - entity: climate.i_c_e_hvac_climate_system
                show_name: false
                title: I.C.E
                type: glance
              - entity: sensor.i_c_e_battery_sensor
                graph: line
                hours_to_show: 72
                type: sensor
              - entity: sensor.i_c_e_range_sensor
                type: gauge
                name: Range
                unit: km
                min: 0
                max: 560
                severity:
                  green: 100
                  yellow: 40
                  red: 0
            type: vertical-stack