title: Casita
resources:
  - url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
    type: module
  - url: local/lovelace/custom-header.js?v=1.7.9
    type: module
  - url: local/lovelace/sidebar-card.js?v=0.0.1
    type: module
sidebar:
  title: "Casita"
  digitalClock: true
  date: true
  sidebarMenu: true
  hideTopMenu: true
  width:
    mobile: 0
    tablet: 25
    desktop: 20
  template: |
    <li>Hello World</li>
  style: |
    :host {
        --sidebar-background: #000;
        --sidebar-text-color: #FFF;
    }
views:
  - badges: []
    title: Overview
    cards:
      - cards:
          - cards:
              - aspect_ratio: '1:1'
                entity: person.joatin
                state_filter:
                  "on": 'brightness(110%) saturate(1.2)'
                  "off": 'brightness(50%) hue-rotate(45deg)'
                entities:
                  - type: divider
                  - entity: person.joatin
                    show_state: true
                image: local/images/joatin.jpeg?v=1
                show_name: false
                show_state: false
                type: picture-glance
                tap_action:
                  action: call-service
                  service: browser_mod.popup
                  service_data:
                    title: Popup example
                    card:
                      entity: weather.smhi_home
                      type: custom:weather-card
                    deviceID:
                      - this
                      - dashboard
              - aspect_ratio: '1:1'
                entity: person.caroline
                image: local/images/caroline.jpeg?v=1
                show_name: false
                show_state: true
                type: picture-entity
            type: horizontal-stack
          - entity: media_player.living_room
            type: media-control
          - entity: weather.smhi_home
            type: custom:weather-card
        type: vertical-stack
      - cards:
          - type: button
            name: Party Time
            show_state: false
            show_icon: true
            icon: fas:laugh-beam
            tap_action:
              action: call-service
              service: script.party
          - type: button
            name: Chill
            show_state: false
            show_icon: true
            icon: mdi:human-female-dance
            tap_action:
              action: call-service
              service: script.party
        type: vertical-stack
  - badges: []
    title: Tesla
    cards:
      - cards:
          - entity: sensor.i_c_e_range_sensor
            type: gauge
            name: Range
            title: I.C.E Battery Range
            unit: km
            min: 0
            max: 560
            severity:
              green: 100
              yellow: 40
              red: 0
          - type: button
            name: Heat Tesla
            show_state: true
            tap_action:
              action: call-service
              service: script.heat_tesla
            hold_action:
              action: toggle
            entity: climate.i_c_e_hvac_climate_system
          - entities:
              - entity: lock.i_c_e_door_lock
              - entity: binary_sensor.i_c_e_charger_sensor
              - entity: climate.i_c_e_hvac_climate_system
            show_name: false
            title: I.C.E
            type: glance
          - entity: sensor.i_c_e_battery_sensor
            graph: line
            hours_to_show: 72
            type: sensor
        type: vertical-stack