title: Casita
resources:
  - url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
    type: module
views:
  - badges: []
    title: Overview
    cards:
      - cards:
          - cards:
              - aspect_ratio: '1:1'
                entity: person.joatin
                image: local/images/joatin.jpeg
                show_name: false
                show_state: true
                type: picture-entity
              - aspect_ratio: '1:1'
                entity: person.caroline
                image: local/images/caroline.jpeg
                show_name: false
                show_state: true
                type: picture-entity
            type: horizontal-stack
          - entity: media_player.living_room
            type: media-control
          - entity: weather.smhi_home
            type: weather-forecast
        type: vertical-stack
      - cards:
          - type: button
            name: Party Time
            show_state: false
            show_icon: true
            icon: fas:laugh-beam
            tap_action:
              action: call-service
              service: script.party
        type: vertical-stack
  - badges: []
    title: Tesla
    cards:
      - cards:
          - entity: sensor.i_c_e_range_sensor
            type: gauge
            name: Range
            title: I.C.E Battery Range
            unit: km
            min: 0
            max: 560
            severity:
              green: 100
              yellow: 40
              red: 0
          - type: button
            name: Heat Tesla
            show_state: true
            tap_action:
              action: call-service
              service: script.heat_tesla
            hold_action:
              action: toggle
            entity: climate.i_c_e_hvac_climate_system
          - entities:
              - entity: lock.i_c_e_door_lock
              - entity: binary_sensor.i_c_e_charger_sensor
              - entity: climate.i_c_e_hvac_climate_system
            show_name: false
            title: I.C.E
            type: glance
          - entity: sensor.i_c_e_battery_sensor
            graph: line
            hours_to_show: 72
            type: sensor
        type: vertical-stack