# Button 1
- alias: "BEDROOM: Wallmote bedroom button 1 'Single Tap'"
  trigger:
    platform: event
    event_type: ozw.scene_activated
    event_data:
      node_id: 5
      scene_id: 1
      scene_value_label: "Pressed 1 Time"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Bedroom
        scene_name: Bright
    - service: hue.hue_activate_scene
      data:
        group_name: Closet
        scene_name: Bright
    - service: light.turn_on
      data:
        entity_id: light.closet
        brightness: 150
    - wait_for_trigger:
        - platform: event
          event_type: ozw.scene_activated
          event_data:
            node_id: 5
            scene_id: 1
            scene_value_label: "Pressed 1 Time"
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.bedroom
    - service: light.turn_off
      data:
        entity_id: light.closet
- alias: "BEDROOM: Wallmote bedroom button 2 'Single Tap'"
  trigger:
    platform: event
    event_type: ozw.scene_activated
    event_data:
      node_id: 5
      scene_id: 2
      scene_value_label: "Pressed 1 Time"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Bedroom
        scene_name: Tropical twilight
    - service: hue.hue_activate_scene
      data:
        group_name: Closet
        scene_name: Tropical twilight
    - wait_for_trigger:
        - platform: event
          event_type: ozw.scene_activated
          event_data:
            node_id: 5
            scene_id: 2
            scene_value_label: "Pressed 1 Time"
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.bedroom
    - service: light.turn_off
      data:
        entity_id: light.closet
- alias: "BEDROOM: Wallmote bedroom button 3 'Single Tap'"
  trigger:
    platform: event
    event_type: ozw.scene_activated
    event_data:
      node_id: 5
      scene_id: 3
      scene_value_label: "Pressed 1 Time"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Bedroom
        scene_name: Savanna sunset
    - service: hue.hue_activate_scene
      data:
        group_name: Closet
        scene_name: Savanna sunset
    - wait_for_trigger:
        - platform: event
          event_type: ozw.scene_activated
          event_data:
            node_id: 5
            scene_id: 3
            scene_value_label: "Pressed 1 Time"
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.bedroom
    - service: light.turn_off
      data:
        entity_id: light.closet
- alias: "BEDROOM: Wallmote bedroom button 4 'Single Tap'"
  trigger:
    platform: event
    event_type: ozw.scene_activated
    event_data:
      node_id: 5
      scene_id: 4
      scene_value_label: "Pressed 1 Time"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Bedroom
        scene_name: Spring blossom
    - service: hue.hue_activate_scene
      data:
        group_name: Closet
        scene_name: Spring blossom
    - wait_for_trigger:
        - platform: event
          event_type: ozw.scene_activated
          event_data:
            node_id: 5
            scene_id: 4
            scene_value_label: "Pressed 1 Time"
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.bedroom
    - service: light.turn_off
      data:
        entity_id: light.closet
- alias: "BEDROOM: Wallmote bedroom button 1 'Hold'"
  mode: restart
  trigger:
    platform: event
    event_type: ozw.scene_activated
    event_data:
      node_id: 5
      scene_id: 1
      scene_value_label: "Key Held down"
  action:
    - service: cover.toggle
      data:
        entity_id: cover.tradfri_blind
- alias: "BEDROOM: Wallmote bedroom button 2 'Hold'"
  mode: restart
  trigger:
    platform: event
    event_type: ozw.scene_activated
    event_data:
      node_id: 5
      scene_id: 2
      scene_value_label: "Key Held down"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Bedroom
        scene_name: Tropical twilight
    - service: hue.hue_activate_scene
      data:
        group_name: Closet
        scene_name: Tropical twilight
    - service: script.sonos_play_list
      data:
        playlist: Party
        media_player: media_player.sonos_living_room
- alias: "BEDROOM: Wallmote bedroom button 3 'Hold'"
  mode: restart
  trigger:
    platform: event
    event_type: ozw.scene_activated
    event_data:
      node_id: 5
      scene_id: 3
      scene_value_label: "Key Held down"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Bedroom
        scene_name: Tropical twilight
    - service: hue.hue_activate_scene
      data:
        group_name: Closet
        scene_name: Tropical twilight
    - service: cover.turn_off
      data:
        entity_id: cover.tradfri_blind
- alias: "BEDROOM: Wallmote bedroom button 4 'Hold'"
  mode: restart
  trigger:
    platform: event
    event_type: ozw.scene_activated
    event_data:
      node_id: 5
      scene_id: 4
      scene_value_label: "Key Held down"
  action:
    - service: homeassistant.toggle
      data:
        entity_id: group.all_light_entities
#Button 3

#Button 4
