# Button 1
- alias: "BEDROOM: Wallmote bedroom button 1 'Single Tap'"
  trigger:
    platform: event
    event_type: zwave_js_event
    event_data:
      node_id: 5
      label: Scene 001
      value: KeyPressed
  action:
    - service: script.turn_on
      data:
    - service: hue.hue_activate_scene
      data:
        group_name: Bedroom
        scene_name: Bright
    - service: hue.hue_activate_scene
      data:
        group_name: Closet
        scene_name: Bright
    - service: light.turn_on
      data:
        entity_id: light.closet
        brightness: 150
    - wait_for_trigger:
        - platform: event
          event_type: zwave_js_event
          event_data:
            node_id: 5
            label: Scene 001
            value: KeyPressed
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.bedroom
    - service: light.turn_off
      data:
        entity_id: light.closet
- alias: "BEDROOM: Wallmote bedroom button 2 'Single Tap'"
  trigger:
    platform: event
    event_type: zwave_js_event
    event_data:
      node_id: 5
      label: Scene 002
      value: KeyPressed
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Bedroom
        scene_name: Tropical twilight
    - service: hue.hue_activate_scene
      data:
        group_name: Closet
        scene_name: Tropical twilight
    - wait_for_trigger:
        - platform: event
          event_type: zwave_js_event
          event_data:
            node_id: 5
            label: Scene 002
            value: KeyPressed
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.bedroom
    - service: light.turn_off
      data:
        entity_id: light.closet
- alias: "BEDROOM: Wallmote bedroom button 3 'Single Tap'"
  trigger:
    platform: event
    event_type: zwave_js_event
    event_data:
      node_id: 5
      label: Scene 003
      value: KeyPressed
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Bedroom
        scene_name: Savanna sunset
    - service: hue.hue_activate_scene
      data:
        group_name: Closet
        scene_name: Savanna sunset
    - wait_for_trigger:
        - platform: event
          event_type: zwave_js_event
          event_data:
            node_id: 5
            label: Scene 003
            value: KeyPressed
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.bedroom
    - service: light.turn_off
      data:
        entity_id: light.closet
- alias: "BEDROOM: Wallmote bedroom button 4 'Single Tap'"
  trigger:
    platform: event
    event_type: zwave_js_event
    event_data:
      node_id: 5
      label: Scene 004
      value: KeyPressed
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Bedroom
        scene_name: Spring blossom
    - service: hue.hue_activate_scene
      data:
        group_name: Closet
        scene_name: Spring blossom
    - wait_for_trigger:
        - platform: event
          event_type: zwave_js_event
          event_data:
            node_id: 5
            label: Scene 004
            value: KeyPressed
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.bedroom
    - service: light.turn_off
      data:
        entity_id: light.closet
- alias: "BEDROOM: Wallmote bedroom button 1 'Hold'"
  mode: restart
  trigger:
    platform: event
    event_type: zwave_js_event
    event_data:
      node_id: 5
      label: Scene 001
      value: KeyReleased
  action:
    - service: cover.toggle
      data:
        entity_id: cover.tradfri_blind
- alias: "BEDROOM: Wallmote bedroom button 2 'Hold'"
  mode: restart
  trigger:
    platform: event
    event_type: zwave_js_event
    event_data:
      node_id: 5
      label: Scene 002
      value: KeyReleased
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Bedroom
        scene_name: Savanna sunset
    - service: hue.hue_activate_scene
      data:
        group_name: Closet
        scene_name: Savanna sunset
    - choose:
        - alias: "If the music is off, turn it on"
          conditions:
            - condition: not
              conditions:
                - condition: state
                  entity_id: media_player.sonos_living_room
                  state: playing
          sequence:
            - service: script.sonos_play_list
              data:
                playlist: Bedroom
                media_player: media_player.sonos_living_room
                volume: 0.2
            - service: cover.close_cover
              data:
                entity_id: cover.tradfri_blind
            - delay: 00:30:00
            - service: media_player.volume_set
              data:
                entity_id: media_player.sonos_living_room
                volume_level: 0.1
            - delay: 00:30:00
            - service: media_player.media_stop
              data:
                media_player: media_player.sonos_living_room
      default:
        - service: media_player.media_stop
          data:
            entity_id: media_player.sonos_living_room
- alias: "BEDROOM: Wallmote bedroom button 3 'Hold'"
  mode: restart
  trigger:
    platform: event
    event_type: zwave_js_event
    event_data:
      node_id: 5
      label: Scene 003
      value: KeyReleased
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Bedroom
        scene_name: Tropical twilight
    - service: hue.hue_activate_scene
      data:
        group_name: Closet
        scene_name: Tropical twilight
    - service: cover.open_cover
      data:
        entity_id: cover.tradfri_blind
- alias: "BEDROOM: Wallmote bedroom button 4 'Hold'"
  mode: restart
  trigger:
    platform: event
    event_type: zwave_js_event
    event_data:
      node_id: 5
      label: Scene 004
      value: KeyReleased
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.all_light_entities
#Button 3

#Button 4
