# Button 1
- alias: "BEDROOM: Wallmote bedroom button 1 'Single Tap'"
  mode: restart
  trigger:
    platform: event
    event_type: ozw.scene_activated
    event_data:
      instance_id: 1
      scene_id: 1
      scene_value_label: "Pressed 1 Time"
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom
- alias: "BEDROOM: Wallmote bedroom button 1 'Hold'"
  mode: restart
  trigger:
    platform: event
    event_type: ozw.scene_activated
    event_data:
      instance_id: 1
      scene_id: 1
      scene_value_label: "Key Held down"
  action:
    - service: light.turn_off
      data:
        entity_id: light.bedroom
#Button 2
- alias: "BEDROOM: Wallmote bedroom button 2 'Single Tap'"
  mode: restart
  trigger:
    platform: event
    event_type: ozw.scene_activated
    event_data:
      instance_id: 1
      scene_id: 2
      scene_value_label: "Pressed 1 Time"
  action:
    - service: cover.toggle
      data:
        entity_id: cover.tradfri_blind
#Button 3
- alias: "BEDROOM: Wallmote bedroom button 3 'Single Tap'"
  mode: restart
  trigger:
    platform: event
    event_type: ozw.scene_activated
    event_data:
      instance_id: 1
      scene_id: 3
      scene_value_label: "Pressed 1 Time"
  action:
    - service: media_player.media_play_pause
      data:
        entity_id: media_player.sonos_living_room
#Button 4
- alias: "BEDROOM: Wallmote bedroom button 4 'Single Tap'"
  mode: restart
  trigger:
    platform: event
    event_type: ozw.scene_activated
    event_data:
      instance_id: 1
      scene_id: 4
      scene_value_label: "Pressed 1 Time"
  action:
    - service: homeassistant.toggle
      data:
        entity_id: group.all_light_entities
