- alias: "LIVING_ROOM: Turn on lights when apple tv is idle"
  trigger:
    platform: state
    entity_id: media_player.living_room_2
    to: 'idle'
    for: '00:00:05'
  condition:
    condition: template
    value_template: "{{ state_attr('media_player.living_room_2', 'app_id') == 'Netflix' }}"
  action:
    - service: light.turn_on
      data:
        entity_id: light.living_room
        brightness: 50
