- alias: "LIVING_ROOM: Turn off lights when apple tv is playing"
  trigger:
    platform: state
    entity_id: media_player.living_room_2
    to: 'playing'
  conditions:
    condition: template
    value_template: "{{ state_attr('media_player.living_room_2', 'app_id') == 'com.netflix.Netflix' }}"
  action:
    - service: light.turn_off
      data:
        entity_id: light.living_room
