# Button 1
- alias: "LIVING_ROOM: Wallmote living room button 1 'Single Tap'"
  trigger:
    platform: event
    event_type: zwave_js_event
    event_data:
      node_id: 9
      label: Scene 001
      value: KeyPressed
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Living Room
        scene_name: Concentrate
    - service: light.turn_on
      data:
        entity_id: light.living_room
        brightness: 255
    - wait_for_trigger:
        - platform: event
          event_type: zwave_js_event
          event_data:
            node_id: 9
            label: Scene 001
            value: KeyPressed
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.living_room
# Button 2
- alias: "LIVING_ROOM: Wallmote living room button 2 'Single Tap'"
  trigger:
    platform: event
    event_type: zwave_js_event
    event_data:
      node_id: 9
      label: Scene 002
      value: KeyPressed
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Living Room
        scene_name: Bright
    - service: light.turn_on
      data:
        entity_id: light.living_room
        brightness: 255
    - wait_for_trigger:
        - platform: event
          event_type: zwave_js_event
          event_data:
            node_id: 9
            label: Scene 002
            value: KeyPressed
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.living_room
# Button 3
- alias: "LIVING_ROOM: Wallmote living room button 3 'Single Tap'"
  trigger:
    platform: event
    event_type: zwave_js_event
    event_data:
      node_id: 9
      label: Scene 003
      value: KeyPressed
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Living Room
        scene_name: Tropical twilight
    - wait_for_trigger:
        - platform: event
          event_type: zwave_js_event
          event_data:
            node_id: 9
            label: Scene 003
            value: KeyPressed
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.living_room
# Button 4
- alias: "LIVING_ROOM: Wallmote living room button 4 'Single Tap'"
  trigger:
    platform: event
    event_type: zwave_js_event
    event_data:
      node_id: 9
      label: Scene 004
      value: KeyPressed
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Living Room
        scene_name: Savanna sunset
    - wait_for_trigger:
        - platform: event
          event_type: zwave_js_event
          event_data:
            node_id: 9
            label: Scene 004
            value: KeyPressed
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.living_room
- alias: "LIVING_ROOM: Wallmote living room button 1 'Hold'"
  mode: restart
  trigger:
    platform: event
    event_type: zwave_js_event
    event_data:
      node_id: 9
      scene_id: 1
      scene_value_label: "Key Held down"
  action:
    - service: cover.toggle
      data:
        entity_id: cover.flush_shutter_dc
