# Button 1
- alias: "LIVING_ROOM: Wallmote living room button 1 'Single Tap'"
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 9
      label: Scene 001
      value: KeyPressed
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Living Room
        scene_name: Concentrate
    - service: light.turn_on
      data:
        entity_id: light.living_room
        brightness: 255
    - wait_for_trigger:
        - platform: event
          event_type: zwave_js_value_notification
          event_data:
            node_id: 9
            label: Scene 001
            value: KeyPressed
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.living_room
# Button 2
- alias: "LIVING_ROOM: Wallmote living room button 2 'Single Tap'"
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 9
      label: Scene 002
      value: KeyPressed
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Living Room
        scene_name: Bright
    - service: light.turn_on
      data:
        entity_id: light.living_room
        brightness: 255
    - wait_for_trigger:
        - platform: event
          event_type: zwave_js_value_notification
          event_data:
            node_id: 9
            label: Scene 002
            value: KeyPressed
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.living_room
# Button 3
- alias: "LIVING_ROOM: Wallmote living room button 3 'Single Tap'"
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 9
      label: Scene 003
      value: KeyPressed
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Living Room
        scene_name: Tropical twilight
    - wait_for_trigger:
        - platform: event
          event_type: zwave_js_value_notification
          event_data:
            node_id: 9
            label: Scene 003
            value: KeyPressed
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.living_room
# Button 4
- alias: "LIVING_ROOM: Wallmote living room button 4 'Single Tap'"
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 9
      label: Scene 004
      value: KeyPressed
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: Living Room
        scene_name: Savanna sunset
    - wait_for_trigger:
        - platform: event
          event_type: zwave_js_value_notification
          event_data:
            node_id: 9
            label: Scene 004
            value: KeyPressed
      timeout: 00:00:03
      continue_on_timeout: false
    - service: light.turn_off
      data:
        entity_id: light.living_room
- alias: "LIVING_ROOM: Wallmote living room button 1 'Hold'"
  mode: restart
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 9
      label: Scene 001
      value: "KeyHeldDown"
  action:
    - service: cover.toggle
      target:
        entity_id: cover.flush_shutter_dc

- alias: "LIVING_ROOM: Wallmote living room button 2 'Hold'"
  mode: restart
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 9
      label: Scene 002
      value: "KeyHeldDown"
  action:
    - alias: "Turn on receiver if off"
      choose:
        - alias: "Receiver is off"
          conditions:
            - condition: state
              entity_id: media_player.receiver
              state: 'off'
          sequence:
            - service: media_player.turn_on
              data: {}
              target:
                entity_id: media_player.receiver
            - service: media_player.turn_on
              data: {}
              target:
                entity_id: media_player.living_room_2
            - service: remote.send_command
              target:
                entity_id: remote.living_room
              data:
                command:
                  - menu
            - service: media_player.onkyo_select_hdmi_output
              data:
                entity_id: media_player.receiver
                hdmi_output: 'yes'
            - service: media_player.select_source
              target:
                entity_id: media_player.receiver
              data:
                source: Bluray
      default:
        - alias: "Switch tv/projector"
          choose:
            - alias: "Projector is off"
              conditions:
                - condition: state
                  entity_id: media_player.epson
                  state: 'off'
              sequence:
                - service: media_player.turn_on
                  data:
                    entity_id: media_player.epson
                - service: media_player.onkyo_select_hdmi_output
                  data:
                    entity_id: media_player.receiver
                    hdmi_output: 'out-sub'
                - service: light.turn_off
                  data:
                    entity_id: light.living_room
          default:
            - service: media_player.turn_off
              data:
                entity_id: media_player.epson
            - service: light.turn_on
              target:
                entity_id: light.living_room
            - service: media_player.onkyo_select_hdmi_output
              data:
                entity_id: media_player.receiver
                hdmi_output: 'yes'

- alias: "LIVING_ROOM: Wallmote living room button 4 'Hold'"
  mode: restart
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 9
      label: Scene 004
      value: "KeyHeldDown"
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.epson
    - service: media_player.turn_off
      data: {}
      target:
        entity_id: media_player.receiver
    - service: media_player.turn_off
      data: {}
      target:
        entity_id: media_player.living_room_2
