- alias: 'test'
  trigger:
    - platform: state
      entity_id: input_boolean.mytest
  action:
    - service: script.sonos_say
      data:
        sonos_entity: 'media_player.living_room'
        volume: 0.5
        message: |
          <speak>
            'Caroline, your husband loves you very very much!'
          </speak>
        delay: '00:00:05'
- alias: Home Assistant Restart Notification
  trigger:
    platform: homeassistant
    event: start
  action:
    - delay: '00:00:05'
    - service: script.sonos_say
      data:
        sonos_entity: 'media_player.living_room'
        volume: 0.5
        message: |
          <speak>
            <amazon:domain name="conversational">
              The home automation system has just restarted.
              Everything will be up and running again within a few moments
            </amazon:domain>
          </speak>
        delay: '00:00:07'
- alias: Morning News Briefing
  trigger:
    platform: time
    at: "08:00:00"
  action:
    - service: script.sonos_say
      data_template:
        sonos_entity: 'media_player.living_room'
        volume: 0.5
        message: |
          <speak>
            <amazon:domain name="conversational">
              Good morning sunshines! The clock is <say-as interpret-as="time" format="hms24">
              {{now().hour}}:{{now().minute}}</say-as>. The weather today will be {{ states('sensor.owm_condition') }}, with
              temperatures reaching <say-as interpret-as="cardinal">
              {{ state_attr('weather.smhi_home', 'temperature') }}</say-as> degrees celsius.
            </amazon:domain>
          </speak>
        delay: '00:00:10'
        cache: false