- alias: "HALLWAY: Announce when someone pressed the doorbell"
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_doorbell
    to: 'on'
  action:
    - service: notify.mobile_app_joatins_iphone
      data:
        title: Knock, knock!
        message: Someone is knocking on the fron door
        data:
          push:
            category: "home_assistant"
          apns_headers:
            'apns-collapse-id': 'restart'
    - service: script.sonos_say
      data:
        sonos_entity: media_player.sonos_living_room
        volume: 0.8
        delay: 00:00:10
        message: <speak>Hello there! Someone is knocking on the front door</speak>
