- alias: "HALLWAY: Turn on lights on front door when there is motion"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_doorbell
    to: 'on'
  action:
    - service: hue.hue_activate_scene
      data_template:
        group_name: front
        scene_name: Bright
    - delay: '00:00:30'
    - service: hue.hue_activate_scene
      data_template:
        group_name: front
        scene_name: Dimmed
