blueprint:
  name: Turn on a hue scene when a time event occurs if the lights are already on
  domain: automation
  input:
    time:
    room:
      name: Hue Room
      description: The hue group name to change the scene within
    scene:
      name: Hue Scene
      description: The hue scene to set
    light:
      name: Light
      description: The light to check whether this room is already lit
trigger:
  platform: event
  event_type: time_event
  event_data:
    time: !input time
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: !input light
      state: 'on'
action:
  service: hue.hue_activate_scene
  data_template:
    group_name: !input room
    scene_name: !input scene
