alias: Turn off lights in closet when there is no motion
trigger:
  platform: state
  entity_id: binary_sensor.closet_sensor_motion
  to: 'off'
  for: '00:00:30'
action:
  - service: scene.turn_on
    data:
      scene_id: light_closet_before
