alias: Turn on the lights when someone arrives at home
trigger:
  platform: template
  value_template: "{{ (trigger.to_state.state.person | selectattr('state','eq','home') | list | count > 0) && (trigger.from_state.state.person | selectattr('state','eq','home') | list | count <= 0) }}"
action:
  - service: light.turn_on
    data:
      entity_id: light.kitchen,light.hallway,light.staircase,light.office,light.bedroom,light.guest_room
