- alias: Change light when door open/closes
  trigger:
    platform: state
    entity_id: binary_sensor.fgdw002_door_opening_sensor_2_access_control_door_window_open
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.fgdw002_door_opening_sensor_2_access_control_door_window_open
              state: 'Open'
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.storage
                brightness: 255
        - conditions:
            - condition: state
              entity_id: binary_sensor.fgdw002_door_opening_sensor_2_access_control_door_window_open
              state: 'Closed'
          sequence:
            - service: light.turn_off
              data:
                entity_id: light.storage
