alias: Turn on lights in closet when there is motion
trigger:
  platform: state
  entity_id: binary_sensor.hue_motion_sensor_1_motion
  to: 'on'
action:
  service: light.turn_on
  entity_id: light.closet
