alias: Turn off the lights when nobody is home
trigger:
  platform: template
  value_template: "{{ states.person | selectattr('state','eq','home') | list | count <= 0 }}"
  for: "00:01:00"
action:
  - service: script.turn_off_lights
