- alias: Switch guest room 'On' press
  trigger:
    platform: event
    event_type: hue_event
    event_data:
      id: guest_room_switch
      event: 4002
  action:
    - service: light.turn_on
      data:
        entity_id: light.hallway
- alias: Switch guest room 'Off' press
  trigger:
    platform: event
    event_type: hue_event
    event_data:
      id: guest_room_switch
      event: 1002
  action:
    - service: light.turn_off
      data:
        entity_id: light.hallway
- alias: Switch guest room 'Off Hold' press
  trigger:
    platform: event
    event_type: hue_event
    event_data:
      id: guest_room_switch
      event: 1001
  action:
    - service: light.turn_on
      data:
        entity_id: light.hallway
        brightness: "{{ state_attr('light.hallway', 'brightness')|int - 5 }}"
- alias: Switch guest room 'Off Hold End' press
  trigger:
    platform: event
    event_type: hue_event
    event_data:
      id: guest_room_switch
      event: 1001
  action:
    - service: light.turn_off
      data:
        entity_id: light.hallway
        brightness: "{{ state_attr('light.hallway', 'brightness')|int - 5 }}"
