# TIME: These automations fires events at important time intervals

- alias: Fire WAKEUP event
  trigger:
    platform: time
    at: "07:00:00"
  action:
    event: time_event
    event_data:
      time: WAKEUP
- alias: Fire MORNING event
  trigger:
    platform: time
    at: "07:00:00"
  action:
    event: time_event
    event_data:
      time: MORNING
- alias: Fire LUNCH event
  trigger:
    platform: time
    at: "11:00:00"
  action:
    event: time_event
    event_data:
      time: LUNCH
- alias: Fire EVENING event
  trigger:
    platform: time
    at: "20:00:00"
  action:
    event: time_event
    event_data:
      time: EVENING
- alias: Fire NIGHT event
  trigger:
    platform: time
    at: "23:00:00"
  action:
    event: time_event
    event_data:
      time: NIGHT
- alias: Fire MIDNIGHT event
  trigger:
    platform: time
    at: "00:00:00"
  action:
    event: time_event
    event_data:
      time: MIDNIGHT
