alias: Turn off the lights when nobody is home
trigger:
  platform: template
  value_template: "{{ (trigger.to_state.state.person | selectattr('state','eq','home') | list | count > 0) && (trigger.from_state.state.person | selectattr('state','eq','home') | list | count <= 0) }}"
  for: "00:01:00"
action:
  - service: light.turn_off
    data:
      entity_id: light.kitchen,light.hallway,light.staircase,light.office,light.bedroom,light.guest_room
