- alias: Update unify ap bedroom led when home assistant starts
  trigger:
    platform: homeassistant
    event: start
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.unify_ap_bedroom_led
              state: 'on'
          sequence:
            - service: shell_command.unifi_ap_bedroom_led_blue
        - conditions:
            - condition: state
              entity_id: input_boolean.unify_ap_bedroom_led
              state: 'off'
          sequence:
            - service: shell_command.unifi_ap_bedroom_led_off
- alias: Update unify ap bedroom led when state changes
  trigger:
    platform: state
    entity_id: input_boolean.unify_ap_bedroom_led
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.unify_ap_bedroom_led
              state: 'on'
          sequence:
            - service: shell_command.unifi_ap_bedroom_led_blue
        - conditions:
            - condition: state
              entity_id: input_boolean.unify_ap_bedroom_led
              state: 'off'
          sequence:
            - service: shell_command.unifi_ap_bedroom_led_off
- alias: Turn off unify ap bedroom led at night
  trigger:
    platform: time
    at: "23:00"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.unify_ap_bedroom_led
- alias: Turn on unify ap bedroom led at morning
  trigger:
    platform: time
    at: "06:00"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.unify_ap_bedroom_led
